version: '3.8'

services:
  data_producer:
    container_name: data_producer
    image: 'data_producer:1.0-SNAPSHOT'
    depends_on:
      - kafka
    restart: always
    ports:
      - '8001:8001'
  data_consumer:
    container_name: data_consumer
    image: 'data_consumer:1.0-SNAPSHOT'
    depends_on:
      - kafka
    restart: always
    ports:
      - '8002:8002'
  data_storage:
    container_name: data_storage
    image: 'data_storage:1.0-SNAPSHOT'
    depends_on:
      - mysql
    restart: always
    ports:
      - '8003:8003'
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mysql:
    image: 'bitnami/mysql:latest'
    volumes:
      - "./initDB.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: unix11
      MYSQL_USER: milagro
      MYSQL_PASSWORD: unix11